### ISSUE TITLE
Heads up for anyone interested in a maintained version of this project

### ISSUE THREAD

**Issue by gubatron** [jrmbchtl/telegram-bot-rs#1]
In case you're having this library do panics on you when parsing "spoiler" messages

I've forked and will be maintaining it here
https://github.com/gubatron/telegram-bot-rs

I've renamed the package to `telegram-api-rs2`
https://crates.io/crates/telegram-api-rs2

Cheers

**Comment by jrmbchtl** [comment]
If you are interested, I can add you as an owner to https://crates.io/crates/telegram-api-rs

**Comment by gubatron** [comment]
(I removed the .nix stuff in my fork though)

Let's do it, I'll try to cherry pick the actual changes that fixed the crashes if you also give me write access here.

**Comment by gubatron** [comment]
that's me
https://crates.io/users/gubatron

**Comment by gubatron** [comment]
Thank you.

Just published with updated `Cargo.toml` pointing to my [fork here on github](https://github.com/gubatron/telegram-bot-rs), so no need to have ownership here.

Changes for 0.0.5 here:
https://github.com/gubatron/telegram-bot-rs/commit/496dbee115880e6ba8d1667b983ee29638eb05c5
